//! Shared geometry for the reference canvas.
//!

/// Transport column (Cue / Play / search)
pub const TRANSPORT_REF_SIZE_H: f32 = 4080.0;
pub const TRANSPORT_REF_SIZE_W: f32 = 510.0;
pub const TRANSPORT_REF_TOP: f32 = 280.0;
pub const TRANSPORT_REF_BOT: f32 = TRANSPORT_REF_TOP + TRANSPORT_REF_SIZE_H;
pub const TRANSPORT_REF_LEFT: f32 = 10.0;
pub const TRANSPORT_REF_RIGHT: f32 = TRANSPORT_REF_LEFT + TRANSPORT_REF_SIZE_W;

// TOP CENTER (MENU, LCD)
pub const TOP_CENTRAL_AFTER_TRANSPORT_GAP: f32 = -40.0;
pub const TOP_CENTRAL_REF_SIZE_H: f32 = 1400.0;
pub const TOP_CENTRAL_REF_SIZE_W: f32 = 2220.0;
pub const TOP_CENTRAL_REF_TOP: f32 = 80.0;
pub const TOP_CENTRAL_REF_BOT: f32 = TOP_CENTRAL_REF_TOP + TOP_CENTRAL_REF_SIZE_H;
pub const TOP_CENTRAL_REF_LEFT: f32 = TRANSPORT_REF_RIGHT + TOP_CENTRAL_AFTER_TRANSPORT_GAP;
pub const TOP_CENTRAL_REF_RIGHT: f32 = TOP_CENTRAL_REF_LEFT + TOP_CENTRAL_REF_SIZE_W;

// MID CENTER (HOT CUE + HELPER ROW)
pub const MID_CENTRAL_AFTER_TOP_CENTRAL_GAP: f32 = 5.0;
pub const MID_CENTRAL_AFTER_TRANSPORT_GAP: f32 = 20.0;
pub const MID_CENTRAL_REF_SIZE_H: f32 = 460.0;
pub const MID_CENTRAL_REF_SIZE_W: f32 =
    TOP_CENTRAL_REF_SIZE_W + (MID_CENTRAL_AFTER_TRANSPORT_GAP * 2.0);
pub const MID_CENTRAL_REF_TOP: f32 = TOP_CENTRAL_REF_BOT + MID_CENTRAL_AFTER_TOP_CENTRAL_GAP;
pub const MID_CENTRAL_REF_BOT: f32 = MID_CENTRAL_REF_TOP + MID_CENTRAL_REF_SIZE_H;
pub const MID_CENTRAL_REF_LEFT: f32 = TOP_CENTRAL_REF_LEFT - MID_CENTRAL_AFTER_TRANSPORT_GAP;
pub const MID_CENTRAL_REF_RIGHT: f32 = MID_CENTRAL_REF_LEFT + MID_CENTRAL_REF_SIZE_W;

// JOG
pub const JOG_AFTER_MID_CENTRAL_GAP: f32 = -30.0;
pub const JOG_REF_SIZE_H: f32 = 2140.0;
pub const JOG_REF_SIZE_W: f32 = 2140.0;
pub const JOG_REF_TOP: f32 = MID_CENTRAL_REF_BOT + JOG_AFTER_MID_CENTRAL_GAP;
pub const JOG_REF_BOT: f32 = JOG_REF_TOP + JOG_REF_SIZE_H;
pub const JOG_REF_LEFT: f32 = TRANSPORT_REF_RIGHT;
pub const JOG_REF_RIGHT: f32 = JOG_REF_LEFT + JOG_REF_SIZE_W;

// NAVIGATION

// MODES
pub const MODE_AFTER_CENTRAL_GAP: f32 = 0.0;
pub const MODE_AFTER_JOG_GAP: f32 = -5.0;
pub const MODES_REF_SIZE_H: f32 = TRANSPORT_REF_SIZE_H;
pub const MODES_REF_SIZE_W: f32 = 520.0;
pub const MODES_REF_TOP: f32 = TRANSPORT_REF_TOP + MODE_AFTER_CENTRAL_GAP;
pub const MODES_REF_BOT: f32 = MODES_REF_TOP + MODES_REF_SIZE_H;
pub const MODES_REF_LEFT: f32 = JOG_REF_RIGHT + MODE_AFTER_JOG_GAP;
pub const MODES_REF_RIGHT: f32 = MODES_REF_LEFT + MODES_REF_SIZE_W;

// BOTTOM DECORATIVE
